###### WiFi Test Suite Daemon Configuration

## Test setup information
name: Test Box 1
location: Room 101
description: A test box in the room 101

## Common configurations
host_daemon: 127.0.0.1
port_daemon: 8270
port_test: 8271
server_url: http://127.0.0.1
server_port: 5000
mongodb_uri: 127.0.0.1
mongodb_port: 27017

test_dir: testlibs
resource_dir: resources

## Windows dependent configurations

## Linux dependent configurations

## Test Suite dependent configurations
iperf2: d:\bin\iperf-2.0.9-win64\iperf2
iperf3: d:\bin\iperf3

## SUT configurations
# Device under test
DUT:
  - name: STA1
    com: COM19
    baudrate: 115200
    # multiple download methods can be configured here, they will be tried one by one if previous one failed
    download:
      # MDK related configurations, details please see http://www.keil.com/support/man/docs/uv4/uv4_commandline.htm.
      - tool: MDK
        path: C:\Keil_v5\UV4\UV4.exe
        workdir: D:\demo-project\
        project: demo.uvproj
        target: demo-target
      - tool: ISP
      - tool: JLink
        path: C:\Program Files (x86)\SEGGER\JLink_V640b\JLink.exe
        interface: SWD
        device: STM32F103C8
        datafile: firmware.bin  # relative to <resource_dir> if it's not an absolute path
        speed: 4000
        flash_addr: 0x08000000

# AP under test
AP:
  # a AP with fixed configuration or a device running openWRT
  - name: totolink_n150
    vendor: RealTek
    product: TOTOLINKN150
    manufacturer: TOTOLINK
    mode: fixed
    url: 'http://192.168.1.1/'
    username: 'admin'
    password: 'admin'
    configuration:
      ssid: totolink_n150
      bssid:
      key_mgmt: WPA2-PSK
      psk: 12345678
  # raspberry pi running OpenWRT firmware
  - name: raspberry pi 1
    mode: auto
    ssh: 192.168.1.100
    com: