from sanic.log import logger
from sanic.response import json

class MyResponse:
	def __init__(self, code, message, data=None):
		self.code = code
		self.message = message
		self.data = data

	def __getitem__(self, key):
		return getattr(self, key)

SUCCESS = MyResponse(20000, 'Success')

USER_NOT_EXIST = MyResponse(50000, 'User does not exist')
USER_ALREADY_EXIST = MyResponse(50001, 'User already exist')
PASSWORD_INCORRECT = MyResponse(50004, 'Password is not correct')
ADMIN_TOKEN_REQUIRED = MyResponse(50007, 'Administrator token is required')
TOKEN_ILLEGAL = MyResponse(50008, 'Token is invalid')
TOKEN_REQUIRED = MyResponse(50009, 'Token is required')
TOKEN_EXPIRED = MyResponse(50014, 'Token is expired')
OTHER_CLIENT_LOGGED_IN = MyResponse(50012, 'Other client has logged in')
NO_TASK_RESOURCES = MyResponse(50013, 'Upload directory is empty')
GIT_ERROR = MyResponse(50100, 'Git runtime error')

UNKNOWN_ERROR = MyResponse(60000, 'Unknown error happened')

EPERM = MyResponse(1, 'Operation not permitted')
ENOENT = MyResponse(2, 'No such file or directory')
ESRCH = MyResponse(3, 'No such process')
EINTR = MyResponse(4, 'Interrupted system call')
EIO = MyResponse(5, 'Input/output error')
ENXIO = MyResponse(6, 'No such device or address')
E2BIG = MyResponse(7, 'Argument list too long')
ENOEXEC = MyResponse(8, 'Exec format error')
EBADF = MyResponse(9, 'Bad file descriptor')
ECHILD = MyResponse(10, 'No child processes')
EAGAIN = MyResponse(11, 'Resource temporarily unavailable, try again')
ENOMEM = MyResponse(12, 'Out of memory')
EACCES = MyResponse(13, 'Permission denied')
EFAULT = MyResponse(14, 'Bad address')
ENOTBLK = MyResponse(15, 'Block device required')
EBUSY = MyResponse(16, 'Device or resource busy')
EEXIST = MyResponse(17, 'File exists')
EXDEV = MyResponse(18, 'Invalid cross-device link')
ENODEV = MyResponse(19, 'No such device')
ENOTDIR = MyResponse(20, 'Not a directory')
EISDIR = MyResponse(21, 'Is a directory')
EINVAL = MyResponse(22, 'Invalid argument')
ENFILE = MyResponse(23, 'File table overflow')
EMFILE = MyResponse(24, 'Too many open files')
ENOTTY = MyResponse(25, 'Not a typewriter')
ETXTBSY = MyResponse(26, 'Text file busy')
EFBIG = MyResponse(27, 'File too large')
ENOSPC = MyResponse(28, 'No space left on device')
ESPIPE = MyResponse(29, 'Illegal seek')
EROFS = MyResponse(30, 'Read-only file system')
EMLINK = MyResponse(31, 'Too many links')
EPIPE = MyResponse(32, 'Broken pipe')
EDOM = MyResponse(33, 'Numerical argument out of domain')
ERANGE = MyResponse(34, 'Numerical result out of range')
EDEADLK = MyResponse(35, 'Resource deadlock would occur')
ENAMETOOLONG = MyResponse(36, 'File name too long')
ENOLCK = MyResponse(37, 'No locks available')
ENOSYS = MyResponse(38, 'Function not implemented')
ENOTEMPTY = MyResponse(39, 'Directory not empty')
ELOOP = MyResponse(40, 'Too many levels of symbolic links')
EWOULDBLOCK = MyResponse(41, 'Operation would block')
ENOMSG = MyResponse(42, 'No message of desired type')
EIDRM = MyResponse(43, 'Identifier removed')
ECHRNG = MyResponse(44, 'Channel number out of range')
EL2NSYNC = MyResponse(45, 'Level = 2 not synchronized')
EL3HLT = MyResponse(46, 'Level = 3 halted')
EL3RST = MyResponse(47, 'Level = 3 reset')
ELNRNG = MyResponse(48, 'Link number out of range')
EUNATCH = MyResponse(49, 'Protocol driver not attached')
ENOCSI = MyResponse(50, 'No CSI structure available')
EL2HLT = MyResponse(51, 'Level = 2 halted')
EBADE = MyResponse(52, 'Invalid exchange')
EBADR = MyResponse(53, 'Invalid request descriptor')
EXFULL = MyResponse(54, 'Exchange full')
ENOANO = MyResponse(55, 'No anode')
EBADRQC = MyResponse(56, 'Invalid request code')
EBADSLT = MyResponse(57, 'Invalid slot')
EDEADLOCK = MyResponse(58, 'Dead lock')
EBFONT = MyResponse(59, 'Bad font file format')
ENOSTR = MyResponse(60, 'Device not a stream')
ENODATA = MyResponse(61, 'No data available')
ETIME = MyResponse(62, 'Timer expired')
ENOSR = MyResponse(63, 'Out of streams resources')
ENONET = MyResponse(64, 'Machine is not on the network')
ENOPKG = MyResponse(65, 'Package not installed')
EREMOTE = MyResponse(66, 'Object is remote')
ENOLINK = MyResponse(67, 'Link has been severed')
EADV = MyResponse(68, 'Advertise error')
ESRMNT = MyResponse(69, 'Srmount error')
ECOMM = MyResponse(70, 'Communication error on send')
EPROTO = MyResponse(71, 'Protocol error')
EMULTIHOP = MyResponse(72, 'Multihop attempted')
EDOTDOT = MyResponse(73, 'RFS specific error')
EBADMSG = MyResponse(74, 'Bad message')
EOVERFLOW = MyResponse(75, 'Value too large for defined data type')
ENOTUNIQ = MyResponse(76, 'Name not unique on network')
EBADFD = MyResponse(77, 'File descriptor in bad state')
EREMCHG = MyResponse(78, 'Remote address changed')
ELIBACC = MyResponse(79, 'Can not access a needed shared library')
ELIBBAD = MyResponse(80, 'Accessing a corrupted shared library')
ELIBSCN = MyResponse(81, '.lib section in a.out corrupted')
ELIBMAX = MyResponse(82, 'Attempting to link in too many shared libraries')
ELIBEXEC = MyResponse(83, 'Cannot exec a shared library directly')
EILSEQ = MyResponse(84, 'Invalid or incomplete multibyte or wide character')
ERESTART = MyResponse(85, 'Interrupted system call should be restarted')
ESTRPIPE = MyResponse(86, 'Streams pipe error')
EUSERS = MyResponse(87, 'Too many users')
ENOTSOCK = MyResponse(88, 'Socket operation on non-socket')
EDESTADDRREQ = MyResponse(89, 'Destination address required')
EMSGSIZE = MyResponse(90, 'Message too long')
EPROTOTYPE = MyResponse(91, 'Protocol wrong type for socket')
ENOPROTOOPT = MyResponse(92, 'Protocol not available')
EPROTONOSUPPORT = MyResponse(93, 'Protocol not supported')
ESOCKTNOSUPPORT = MyResponse(94, 'Socket type not supported')
EOPNOTSUPP = MyResponse(95, 'Operation not supported')
EPFNOSUPPORT = MyResponse(96, 'Protocol family not supported')
EAFNOSUPPORT = MyResponse(97, 'Address family not supported by protocol')
EADDRINUSE = MyResponse(98, 'Address already in use')
EADDRNOTAVAIL = MyResponse(99, 'Cannot assign requested address')
ENETDOWN = MyResponse(100, 'Network is down')
ENETUNREACH = MyResponse(101, 'Network is unreachable')
ENETRESET = MyResponse(102, 'Network dropped connection on reset')
ECONNABORTED = MyResponse(103, 'Software caused connection abort')
ECONNRESET = MyResponse(104, 'Connection reset by peer')
ENOBUFS = MyResponse(105, 'No buffer space available')
EISCONN = MyResponse(106, 'Transport endpoint is already connected')
ENOTCONN = MyResponse(107, 'Transport endpoint is not connected')
ESHUTDOWN = MyResponse(108, 'Cannot send after transport endpoint shutdown')
ETOOMANYREFS = MyResponse(109, 'Too many references: cannot splice')
ETIMEDOUT = MyResponse(110, 'Connection timed out')
ECONNREFUSED = MyResponse(111, 'Connection refused')
EHOSTDOWN = MyResponse(112, 'Host is down')
EHOSTUNREACH = MyResponse(113, 'No route to host')
EALREADY = MyResponse(114, 'Operation already in progress')
EINPROGRESS = MyResponse(115, 'Operation now in progress')
ESTALE = MyResponse(116, 'Stale NFS file handle')
EUCLEAN = MyResponse(117, 'Structure needs cleaning')
ENOTNAM = MyResponse(118, 'Not a XENIX named type file')
ENAVAIL = MyResponse(119, 'No XENIX semaphores available')
EISNAM = MyResponse(120, 'Is a named type file')
EREMOTEIO = MyResponse(121, 'Remote I/O error')
EDQUOT = MyResponse(122, 'Disk quota exceeded')
ENOMEDIUM = MyResponse(123, 'No medium found')
EMEDIUMTYPE = MyResponse(124, 'Wrong medium type')
ECANCELED = MyResponse(125, 'Operation canceled')
ENOKEY = MyResponse(126, 'Required key not available')
EKEYEXPIRED = MyResponse(127, 'Key has expired')
EKEYREVOKED = MyResponse(128, 'Key has been revoked')
EKEYREJECTED = MyResponse(129, 'Key was rejected by service')
EOWNERDEAD = MyResponse(130, 'Owner died')
ENOTRECOVERABLE = MyResponse(131, 'State not recoverable')

def response_message(error, message=None, **payload):
	message = message if message else error.message
	if error.code != 20000:
		logger.error(message)
	else:
		logger.info(message)
	ret = {
		'code': error.code,
		'message': message,
        'data': payload
	}
	return ret
