### WiFi Test Suite Agent Configuration

# Test setup information
name: Test Box 1
group: Room 703
description: A test box in the room 703

host_agent: 127.0.0.1
port_agent: 8270
port_test: 8271
server_url: http://127.0.0.1
server_port: 3000
test_dir: testlibs
iperf2: d:\\bin\\iperf-2.0.9-win64\\iperf2
iperf3: d:\\bin\\iperf3

# Device under test
DUT:
  - name: STA1
    com: COM9
    baudrate: 115200
    download:
      - keil
      - ISP
  - name: STA2
    com: COM11
    baudrate: 115200

# AP under test
AP:
  # a AP with fixed configuration or a device running openWRT
  - name: TL-WR886N
    mode: fixed
    configuration:
      ssid: tplink886-wpa2
      bssid:
      key_mgmt: WPA-PSK
      psk: 12345678
  # raspberry pi running OpenWRT firmware
  - name: raspberry pi 1
    mode: auto
    telnet: 192.168.1.100
    com:
